"""Stable context section definitions."""

SECTION_ORDER = ["PROJECT", "VERSION", "ARCHITECTURAL_SMELL", "AFFECTED_COMPONENT", "CENTRAL_COMPONENT", "AFFECTED_ELEMENTS", "SMELL_CHARACTERISTICS", "COMPONENT_METRICS", "ENGINEERED_INDICATORS", "PROPOSED_REFACTORING", "REFACTORING_DESCRIPTION", "INTENDED_EFFECT", "CONTRAINDICATIONS"]

